version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: elasticsearch
    networks:
      - elastic-jaeger
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    environment:
      - node.name=elasticsearch
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kafka:
    image: confluentinc/cp-kafka:5.0.1
    ports:
      - "9092:9092"
    networks:
      - elastic-jaeger
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "jaeger-spans"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1
    ports:
      - "2181:2181"
    networks:
      - elastic-jaeger
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.16
    ports:
      - "14269:14269"
      - "14268:14268"
      - "14267:14267"
      - "9411:9411"
    networks:
      - elastic-jaeger
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: kafka
      KAFKA_BROKERS: "kafka:9092"
    command: [
      "--kafka.producer.brokers=kafka:9092",
      "--kafka.producer.topic=jaeger-spans",
      "--log-level=error"
    ]

  jaeger-ingester:
    image: jaegertracing/jaeger-ingester:1.16
    command: [
      "--log-level=debug",
      "--es.server-urls=http://172.18.21.145:9200",
      "--kafka.consumer.brokers=kafka:9092",
      "--kafka.consumer.protocol-version=0.9.0.0",
      "--kafka.consumer.topic=jaeger-spans"] # plain json payload
    networks:
      - elastic-jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    ports:
      - 14270:14270
      - 14271:14271
    restart: on-failure

  jaeger-agent:
    image: jaegertracing/jaeger-agent:1.16
    hostname: jaeger-agent
    command: ["--collector.host-port=jaeger-collector:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
    networks:
      - elastic-jaeger
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: kafka
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "jaeger-spans"
  
  jaeger-query:
    image: jaegertracing/jaeger-query:1.16
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - no_proxy=localhost
    ports:
      - "16686:16686"
      - "16687:16687"
    networks:
      - elastic-jaeger
    restart: on-failure
    command: [
      "--es.server-urls=http://172.18.21.145:9200",
      "--span-storage.type=elasticsearch",
      "--log-level=debug"
    ]

volumes:
  esdata:
    driver: local

networks:
  elastic-jaeger:
    driver: bridge 